apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ppkuxd44w-go 
  janus-idp.io/tekton: ppkuxd44w-go
  backstage.io/kubernetes-id: ppkuxd44w-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ppkuxd44w-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  